version: "3.3"

services:
  db:
    image: postgres:14-alpine
    container_name: "database"
    environment:
      POSTGRES_DB: "smit"
      POSTGRES_USER: "tester"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    networks:
      - fullstack
    restart: always
    volumes:
      - database_postgres:/var/lib/postgresql/data

  web:
    build: .
    container_name: "rest_api"
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - fullstack
    restart: always

volumes:
  database_postgres:

networks:
  fullstack:
    driver: bridge